# Generated by Django 6.0.1 on 2026-02-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tite',
            new_name='title',
        ),
    ]
